# Default htscodecs.mk generated by Makefile
include $(HTSPREFIX)htscodecs_bundled.mk
# Compiler probe results, generated by ./hts_probe_cc.sh
HTS_CFLAGS_SSE4 = -mpopcnt -msse4.1 -mssse3
HTS_CFLAGS_AVX2 = -mavx2
HTS_CFLAGS_AVX512 = -mavx512f
